import { useQuery, useQueryClient } from "@tanstack/react-query";
import { directus } from "@/lib/directus";
import { readItems, createItem, updateItem } from "@directus/sdk";
import { useEffect } from "react";
import { toast } from "sonner";

export interface OperationalAlert {
  id: string;
  alert_type: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  entity_type?: string;
  entity_id?: string;
  title: string;
  description?: string;
  action_required?: string;
  is_resolved: boolean;
  resolved_at?: string;
  resolved_by?: string;
  created_at: string;
}

export function useOperationalAlerts() {
  const queryClient = useQueryClient();

  const { data: alerts = [], isLoading } = useQuery({
    queryKey: ['operational_alerts'],
    queryFn: async () => {
      try {
        const data = await directus.request(readItems('operational_alerts', {
          sort: ['-created_at' as any] // Using system created_at as date field wasn't explicit in my script but Directus adds it by default
        }));
        return data as unknown as OperationalAlert[];
      } catch (err) {
        console.error("Error fetching alerts:", err);
        return [];
      }
    },
  });

  const resolveAlert = async (alertId: string) => {
    try {
      await directus.request(updateItem('operational_alerts', alertId, {
        is_resolved: true,
        resolved_at: new Date().toISOString()
      }));
      toast.success('Alerta resolvido!');
      queryClient.invalidateQueries({ queryKey: ['operational_alerts'] });
    } catch (err) {
      console.error("Error resolving alert:", err);
      toast.error('Erro ao resolver alerta');
    }
  };

  const createAlert = async (alert: Omit<OperationalAlert, 'id' | 'created_at' | 'is_resolved'>) => {
    try {
      await directus.request(createItem('operational_alerts', {
        ...alert,
        is_resolved: false
      }));
      // toast.success('Alerta gerado'); // Usually alerts are generated by system, avoiding toast spam
      queryClient.invalidateQueries({ queryKey: ['operational_alerts'] });
    } catch (err) {
      console.error("Error creating alert:", err);
    }
  };

  const criticalAlerts = alerts.filter(a => a.severity === 'critical' && !a.is_resolved);
  const highAlerts = alerts.filter(a => a.severity === 'high' && !a.is_resolved);
  const mediumAlerts = alerts.filter(a => a.severity === 'medium' && !a.is_resolved);
  const lowAlerts = alerts.filter(a => a.severity === 'low' && !a.is_resolved);

  return {
    alerts,
    criticalAlerts,
    highAlerts,
    mediumAlerts,
    lowAlerts,
    isLoading,
    resolveAlert,
    createAlert,
  };
}
